### PR TITLE
Fix import from CJS lib

### LINKED ISSUE #238: ERROR import {sync as globSync} from 'fast-glob';
After installing in my project ESLint is now throwing this error.

I haven't ever had anything like this with plugins. 
How do I troubleshoot? Thanks.

```bash
Uncaught exception received.
file:///Users/jeremy/dev/__active/eslint-plugin-awesome-labs/node_modules/eslint-import-resolver-typescript/lib/index.js:6
import { sync as globSync } from 'fast-glob';
         ^^^^
SyntaxError: Named export 'sync' not found. The requested module 'fast-glob' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'fast-glob';
const { sync: globSync } = pkg;
```

### PR DESCRIPTION
**Pull request by klippx**
Fixes #238

### CODE REVIEW

**Comment by klippx** [comment]
Only problem is CI isn't running... Package.json says
```json
"packageManager": "pnpm@8.0.0",
```

And I am running on latest:
```sh
> eslint-import-resolver-typescript % pnpm -v
8.6.1
```

And it works:
```sh
eslint-import-resolver-typescript % pnpm i --frozen-lockfile
Lockfile is up to date, resolution step is skipped
Already up to date

> eslint-import-resolver-typescript@3.6.0 prepare /Users/MKLIPPIN/repos/eslint-import-resolver-typescript
> simple-git-hooks

[INFO] Successfully set the pre-commit with command: pnpm lint-staged
[INFO] Successfully set the commit-msg with command: pnpm commitlint -e
[INFO] Successfully set all git hooks
Done in 917ms
```

And I have committed the latest changes to pnpm-lock as per https://pnpm.io/errors#err_pnpm_outdated_lockfile

So something is weird in this repo? Or you need to specify how contributors are supposed to get the "correct" version of pnpm.

I have also tried installing EXACTLY 8.0.0 (which is a huge hassle) but it was the same, CI is broken.

File: src/index.ts [hunk 1]
```diff
@@ -5,12 +5,14 @@ import debug from 'debug'
 import type { FileSystem, ResolveOptions, Resolver } from 'enhanced-resolve'
 import enhancedResolve from 'enhanced-resolve'
 import { hashObject } from 'eslint-module-utils/hash.js'
-import { sync as globSync } from 'fast-glob'
+import FastGlob from 'fast-glob'
```
Comment (JounQin) [inline src/index.ts:8]:
```suggestion
import fg from 'fast-glob'
```

https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#synchronous

It seems `fg.globSync` is available.
