### PR TITLE
fix: force tiniglobby to expand dot directories

### LINKED ISSUE #359: Unable to resolve path to module with aliases.
Starting from `tinyglobby@^0.2.11`, `eslint-import-resolver-typescript` is unable to resolve module paths when using aliases. As a workaround, I had to override `tinyglobby` to version `0.2.10` to restore functionality.  

This issue can be reproduced in my pull request https://github.com/DTS-STN/future-sir/pull/226 with commit https://github.com/DTS-STN/future-sir/commit/e1da254, where the problem occurs. The next commit https://github.com/DTS-STN/future-sir/commit/f0e3ce2 includes the override, which resolves the issue.

Image

### PR DESCRIPTION
**Pull request by carlocorradini**
Fixes #359, #361

Added three new tests:
1. `dotInclude`
   Search files in _dot_ directories defined in tsconfig.json `include`
1. `dotPaths`
   Resolve tsconfig.json `paths` under _dot_ directories
1. `dotProject`
   Search tsconfig.json files under _dot_ directories (via glob pattern)

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -402,9 +402,10 @@ function initMappers(options: InternalResolverOptions) {
       ...globSync(
         configPaths.filter(path => isDynamicPattern(path)),
         {
+          absolute: true,
```
Comment (JounQin) [inline src/index.ts:405]: Do we also need `cwd` here considering #348?

Comment (JounQin) [reply src/index.ts:405]: Why is this marked as resolved without comment? @carlocorradini

**Comment by carlocorradini** [comment]
@JounQin I've also updated `tinyglobby` to latest version (fix issue #361)

**Comment by JounQin** [comment]
@carlocorradini Would you like to check https://github.com/import-js/eslint-import-resolver-typescript/pull/360#discussion_r1961519170?

**Comment by carlocorradini** [comment]
> @carlocorradini Would you like to check [#360 (comment)](https://github.com/import-js/eslint-import-resolver-typescript/pull/360#discussion_r1961519170)?

You can't see my comments? Is this a GitHub bug?

image

**Comment by JounQin** [comment]
@carlocorradini According to your snapshot, your comments are all `pending` to be finished.

**Comment by carlocorradini** [comment]
@JounQin Now?
