### PR TITLE
fix: include options hash in cache key for options normalization

### LINKED ISSUE #465: Caching results in wrong configuration being used
## Reproduction

Consider this test project: [test.zip](https://github.com/user-attachments/files/20887726/test.zip)[^1]

1. Run `pnpm install` (or `npm install` if you'd rather).
2. Run `pnpm exec eslint` (or `npm exec eslint`).

## Expected results

Linting runs with no issues reported.

## Actual results

There will be an error. It's random whether it's
```
/tmp/test/src/a.foo.js
  1:15  error  Unable to resolve path to module './x'  import/no-unresolved
```
or
```
/tmp/test/src/a.bar.js
  1:15  error  Unable to resolve path to module './y'  import/no-unresolved
```

## Analysis

The eslint configuration in that test project configures the `extensions` for `.foo.js` files to prefer including other `.foo.js` files, and for `.bar.js` files to prefer including other `.bar.js` files.[^2]

The problem appears to be in https://github.com/import-js/eslint-import-resolver-typescript/blob/c06392fcb4c6445e720db326475e3fe0b0814229/src/normalize-options.ts#L79-L85
If `configFile` is set, it caches and reuses options with that filename as a key, without considering that the passed-in `options` may be different. Therefore, the options for whichever of `.foo.js` or `.bar.js` happens to get there first are used for both types of files.

[^1]: Note the problem also happens if `eslint-plugin-import` is replaced with `eslint-plugin-import-x` and configuration is adjusted accordingly.
[^2]: The real-world version of this is our configuration for linting React Native code, where `.native.js` files want to include other `.native.js`. Having both `.foo.js` and `.bar.js` in the reproduction makes it always error on one file or the other.

### PR DESCRIPTION
**Pull request by anomiex**
Presumably to avoid excessive stat calls, the return value of `normalizeOptions()` is cached for each input tsconfig file. But the return value also depends on the input `options`: eslint configuration may pass different options for the same tsconfig file.

To fix it, include a hash of the `options` in the cache key too.

Fixes #465

----

> [!IMPORTANT]
> Modify `normalizeOptions()` to cache only filename lookup, ensuring correct handling of different options for the same tsconfig file, and add tests for verification.
> 
>   - **Behavior**:
>     - Modify `normalizeOptions()` in `normalize-options.ts` to cache only the filename lookup, not the entire options object.
>     - Ensures different options for the same tsconfig file are handled correctly.
>   - **Tests**:
>     - Add `filesWithDifferentOptions` test case in `e2e.spec.ts.snap` to verify behavior with different file extensions.
>     - New test files `eslint.config.js`, `a.bar.js`, `a.foo.js`, `x.foo.js`, `y.bar.js` added under `tests/e2e/filesWithDifferentOptions/` to support the new test case.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=import-js%2Feslint-import-resolver-typescript&utm_source=github&utm_medium=referral)<sup> for 614f3b2dfcb27dc640766d3579144ed947b51b1e. You can [customize](https://app.ellipsis.dev/import-js/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

## Summary by CodeRabbit

- **Bug Fixes**
  - Enhanced caching to accurately differentiate option sets, improving import resolution reliability.

- **Tests**
  - Added test files and ESLint configurations to validate import resolution for `.foo.js` and `.bar.js` extensions.
  - Included sample modules to support these new test scenarios.

- **Chores**
  - Added a changeset documenting the patch update and its impact.

### CODE REVIEW

**Review by JounQin — CHANGES_REQUESTED** [review]
Thanks for working on this first, but the better fix would be move the `optionsHash` check from https://github.com/import-js/eslint-import-resolver-typescript/blob/c06392fcb4c6445e720db326475e3fe0b0814229/src/index.ts#L83 to `normalizeOptions` instead, makes the cache key into `configFile + '\0' + optionsHash`.

**Comment by anomiex** [comment]
Ok, we can do it that way. 🤷

I didn't _move_ the check though, because the separate cache in `src/index.ts` still needs it too.

File: src/normalize-options.ts [hunk 1]
```diff
@@ -76,10 +77,16 @@ export function normalizeOptions(
...
+  const optionsHash = stableHash(options)
   if (configFile) {
-    const cachedOptions = configFileMapping.get(configFile)
+    const cachedOptions = configFileMapping.get(`${configFile}\0${optionsHash}`)
     if (cachedOptions) {
-      log('using cached options for', configFile)
+      log(
+        'using cached options for',
+        configFile,
+        'with options hash',
```
Comment (JounQin) [inline src/normalize-options.ts]:
```suggestion
        'with options',
```

I don't think `options hash` make sense here, we should display `options` instead.

File: src/normalize-options.ts [hunk 2]
```diff
@@ -76,10 +77,16 @@ export function normalizeOptions(
     ensured = true
   }
 
+  const optionsHash = stableHash(options)
   if (configFile) {
-    const cachedOptions = configFileMapping.get(configFile)
+    const cachedOptions = configFileMapping.get(`${configFile}\0${optionsHash}`)
```
Comment (JounQin) [inline src/normalize-options.ts]: Let's add a variable `cacheKey` outside.

**Review by JounQin — CHANGES_REQUESTED** [review]

File: src/normalize-options.ts (hunk 1 above)
Comment (anomiex) [reply src/normalize-options.ts]: 769f6a6

File: src/normalize-options.ts (hunk 2 above)
Comment (anomiex) [reply src/normalize-options.ts]: 769f6a6

**Review by JounQin — APPROVED** [review]
LGTM
